language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '7'
  - '6'
before_script:
  - npm prune
script:
  - npm run test
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - bash <(curl -s https://codecov.io/bash)
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
language: node_js
services:
  - mongodb
